language: objective-c
osx_image: xcode10.1
branches:
  only:
    - master
env:
  global:
    - LANG=en_US.UTF-8
    - WORKSPACE=Example/FRLabel.xcworkspace
    - SCHEME="FRLabel-Example"
    - DESTINATION="OS=12.1,name=iPhone X"
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
